import Head from 'next/head'
import Image from 'next/image'
import bell from "../../public/bell.svg"
import { Inter } from '@next/font/google'
import LinkAirModal from "../components/LinkAirModal";
import {useSelector, useDispatch} from "react-redux";
import {useState, useEffect} from "react";
import { openModal,addPhoneNumber } from '@/features/modalSlice';
import {BsChevronRight} from "react-icons/bs";

export default function Home() {
  const dispatch = useDispatch()
  const [isOpen, setIsOpen] = useState(false);
  const [phoneNumber, setPhoneNumber] = useState('');
  const [countryData, setCountryData] = useState(null);


  useEffect(() => {
    const fetchData = async () => {
      const req = await fetch('https://ipapi.co/json/');
      const res = await req.json();
      setCountryData(res);
    }
    fetchData();

      setTimeout(() => {
        if(localStorage.getItem('firstVisit') === null) {
          localStorage.setItem('firstVisit', false);
          setIsOpen(true);
        }
        }, 5000);
        
  }, [])
  
  const submitHandler = (e) => {
    e.preventDefault();
    if(phoneNumber !== null) {
      dispatch(addPhoneNumber(phoneNumber));
      setIsOpen(false);
  }
  }

  return (
    <>
      <Head>
        <title>LinkAir Modal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
     <LinkAirModal isOpen={isOpen}>
    <button className="close-btn" 
    onClick={() => setIsOpen(false)}>
      Inchide
    </button>
        <Image src={bell} alt="bell"/>
        <h2>ACUM, poti zbura mai ieftin!</h2>
        <p>Prin numar de telefon obtii oferte direct de la companiile Aeriene!</p>
      <form onSubmit={submitHandler}>
        <div className="form-control">
          <select>
            <option value={countryData?.country}>{countryData?.country}</option>
          </select>
          <p>{countryData?.country_calling_code}</p>
      <input type="text" 
      onChange={(e) => setPhoneNumber(e.target.value)}
        value={phoneNumber}
        placeholder="Introduceti Numarul"/>
      </div>
      <button className="submit-btn" type="submit">Afla acum <BsChevronRight/></button>
      </form>
      </LinkAirModal>
      </main>
    </>
  )
}
